name: Build & Test

on:
  push:
    branches: [master, develop, "feat/*"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"

jobs:
  e2e-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: "Install dependencies"
        run: npm install
      - name: "Run tests"
        run: npm test

